require 'rugged'
require 'poper/runner'
require 'poper/rule/rule'
require 'poper/rule/capitalization'
require 'poper/rule/single_word'
require 'poper/rule/fifty_char_summary'
require 'poper/rule/seventy_two_char_limit'
